#!/usr/bin/env bash

[ ! -e "$XDG_CONFIG_HOME/dotfiles/eth" ] && echo "Please create a directory $XDG_CONFIG_HOME/dotfiles/eth that contains a file named after your Ethernet device, or you can symlink a sysfs folder, e.g. /sys/devices/pci0000:00/0000:00:1c.1/0000:03:00.0/net" && exit 1

DOTFILES="$(cat "$XDG_CONFIG_HOME/dotfiles/dotfiles")"
PUBIF="$(ls "$XDG_CONFIG_HOME/dotfiles/eth")" "$DOTFILES/networks/client"
