#!/usr/bin/env bash

URL="$1"
TARGET="$2"
HOOK="$3"

function rl {
  local TARGET_FILE=$1
  cd "$(dirname "$TARGET_FILE")"
  TARGET_FILE=$(basename "$TARGET_FILE")
  while [ -L "$TARGET_FILE" ]
  do
    TARGET_FILE=$(readlink "$TARGET_FILE")
    cd "$(dirname "$TARGET_FILE")"
    TARGET_FILE=$(basename "$TARGET_FILE")
  done
  echo "$(pwd -P)/$TARGET_FILE"
}
SELF="$(rl "$0")"
SCRIPTS="$(dirname "$SELF")"

if [ -z "$URL" ]
then
    echo "URL undefined" 1>&2
    exit 1
fi

if [ -z "$TARGET" ]
then
    echo "Target undefined" 1>&2
    exit 1
fi

if [ -e "$TARGET" ]
then
    echo "Target $TARGET already exists" 1>&2
    exit 1
fi

TARGET="$(realpath "$TARGET")"
TRIESTOHOOK=3
echo "Downloading metadata"
phantomjs "$SCRIPTS/meta.js" "$URL" | (
    read PREFIX
    read ID
    read COOKIE
    read PAGES
    DIR="$(mktemp --directory)"
    cd "$DIR"
    echo "Downloading the faux page"
    "$SCRIPTS/download-page" "faux.pdf" "1" "$ID" "$URL" "foobar" "$SCRIPTS" "$PREFIX"
    pdftotext faux.pdf
    TRY=0
    for PAGE in $(seq 1 $PAGES)
    do
        echo "Page $PAGE of $PAGES"
        cp "faux.txt" "${PAGE}.txt"
        while diff "${PAGE}.txt" "faux.txt" >/dev/null
        do
            if [ "$TRY" == "$TRIESTOHOOK" ]
            then
                echo "Hooking"
                "$HOOK" "$URL" "$COOKIE"
                TRY=0
            elif [ "$TRY" != "0" ]
            then
                echo "Retrying"
            fi
            "$SCRIPTS/download-page" "${PAGE}.pdf" "$PAGE" "$ID" "$URL" "$COOKIE" "$SCRIPTS" "$PREFIX"
            pdftotext "${PAGE}.pdf"
            TRY=$((TRY + 1))
        done
        rm "${PAGE}.txt"
    done
    rm faux.pdf faux.txt
    echo "Concatenating"
    pdftk $(ls -t1r) cat output "$TARGET"
    cd /
    rm -rf "$DIR"
)
