#!/usr/bin/env bash

TARGET="$1"
PAGE="$2"
ID="$3"
REFERER="$4"
COOKIE="$5"
PREFIX="$6"
URLPREFIX="$7"

USERAGENT="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1650.57 Safari/537.36"
URL="${URLPREFIX}?format=swf&data=$ID&page=$PAGE"
DIR="$(mktemp --directory)"

if [ -z "$TARGET" ]
then
    echo "Target undefined" 1>&2
    exit 1
fi

if [ -z "$PAGE" ]
then
    echo "Page undefined" 1>&2
    exit 1
fi

if [ -e "$TARGET" ]
then
    echo "Target $TARGET already exists" 1>&2
    exit 1
fi

TARGET="$(readlink --canonicalize "$TARGET")"
cd "$DIR" || exit 1

echo "Downloading"
wget --header="Cookie: $COOKIE" --header="Referer: $REFERER" --header="User-Agent: $USERAGENT" "$URL" -O input.swf 2>/dev/null || exit 1

echo "Extracting text layer"
cd "$PREFIX"
LIBS="/usr/lib/x86_64-linux-gnu/libmp3lame.so:/usr/lib/x86_64-linux-gnu/libfreetype.so:/usr/lib/x86_64-linux-gnu/libjpeg.so:/usr/lib/libzzip.so"
#LIBS="/usr/lib/libmp3lame.so:/usr/lib/libfreetype.so:/usr/lib/libjpeg.so:/usr/lib/libzzip.so"
echo -e "import swf_to_pdf\nswf_to_pdf.to_pdf([swf_to_pdf.parse_swf('$DIR/input.swf')], '$DIR/text.pdf')\n" | LD_PRELOAD="$LIBS" python2 || exit 1
cd "$DIR"

echo "Extracting visual layer"
"$PREFIX/gfx2gfx" -v input.swf -o visual.pdf 1>/dev/null 3>&1 2>&1 || exit 1

echo "Combining into target"
pdftk visual.pdf background text.pdf output "$TARGET" || exit 1

cd /
rm -rf "$DIR"
