#!/usr/bin/env bash

LEFT="DP-2-1"
CENTER="DP-2-3"
RIGHT="eDP-1"

xrandr \
  --output "$LEFT" --auto  --rotate left \
  --output "$CENTER" --auto --rotate normal --right-of "$LEFT" --preferred --primary \
  --output "$RIGHT" --auto --rotate normal --right-of "$CENTER" \
  || exit 1
