#!/usr/bin/env bash

LEFT="eDP-1"
CENTER="DP-2-3"
RIGHT="DP-2-1"

xrandr  --output "$LEFT" --mode 1920x1080 --pos 1920x0 --rotate normal \
  --output "$CENTER" --mode 1920x1200 --pos 0x0 --rotate normal --primary \
  --output "$RIGHT" --mode 1920x1200 --pos 3840x0 --rotate normal || exit 1
xrandr  --output "$LEFT" --mode 1920x1080 --pos 0x0 --rotate normal \
  --output "$CENTER" --mode 1920x1200 --pos 1920x0 --rotate normal --primary \
  --output "$RIGHT" --mode 1920x1200 --pos 3840x0 --rotate normal || exit 1
