#!/usr/bin/env bash

CENTER="DP-1"
RIGHT="eDP-1"

xrandr \
  --output "$CENTER" --auto --rotate normal --preferred --primary \
  --output "$RIGHT" --auto --rotate normal --right-of "$CENTER" \
  || exit 1
