#!/usr/bin/env bash

LEFT="DP2-1"
CENTER="DP2-3"

xrandr --output "$LEFT" --mode 1920x1200 --pos 1920x0 --rotate normal \
  --output "$CENTER" --mode 1920x1200 --pos 0x0 --rotate normal --primary && \
xrandr  --output "$LEFT" --mode 1920x1200 --pos 0x0 --rotate normal \
  --output "$CENTER" --mode 1920x1200 --pos 1920x0 --rotate normal --primary || exit 1
