#!/usr/bin/env bash

FIRST="$1"
SECOND="$2"

xrandr \
  --output "$FIRST" --auto --rotate normal --preferred --primary \
  --output "$SECOND" --auto --rotate normal --below "$FIRST"

xrandr --newmode 1920x1080_60.00 173.00 1920 2048 2248 2576 1080 1083 1088 1120 -hsync +vsync
xrandr --addmode "$SECOND" 1920x1080_60.00
xrandr --output "$SECOND" --mode 1920x1080_60.00
