#!/usr/bin/env bash

LEFT="$1"
CENTER="$2"
RIGHT="$3"

xrandr \
  --output "$LEFT" --auto  --rotate left \
  --output "$CENTER" --auto --rotate normal --right-of "$LEFT" --preferred --primary \
  --output "$RIGHT" --auto --rotate normal --right-of "$CENTER" \
  || exit 1
