#!/usr/bin/env bash

xrandr \
  --output HDMI-1 --auto --rotate normal --preferred --primary \
  --output DP-2-2 --auto --rotate normal --right-of HDMI-1 \
  --output eDP-1 --auto --rotate normal --below HDMI-1
