#!/usr/bin/env bash

xrandr --output HDMI1 --preferred --primary --auto --rotate normal --above eDP1 --output eDP1 --auto --rotate normal --output VGA1 --auto --rotate normal --left-of HDMI1
xset s on
xset s blank
xset s 300
