#!/usr/bin/env bash

xrandr \
  --output HDMI1 --auto --rotate normal --preferred --primary \
  --output DP2-2 --auto --rotate normal --right-of HDMI1 \
  --output eDP1 --auto --rotate normal --below HDMI1
