#!/usr/bin/env bash

FIRST="$1"
SECOND="$2"
THIRD="$3"

xrandr \
  --output "eDP-1" --off \
  --output "$FIRST" --auto --rotate normal --preferred --primary \
  --output "$SECOND" --auto --rotate right --right-of "$FIRST" \
  --output "$THIRD" --auto --rotate left --left-of "$FIRST"
