#!/usr/bin/env bash

FIRST="eDP-1"
SECOND="$1"
if [ "$SECOND" = "" ]
then
  SECOND="HDMI-1"
fi

xrandr \
  --output "$SECOND" --auto --rotate normal --preferred --primary \
  --output "$FIRST" --auto --rotate normal --below "$SECOND"
