FROM ubuntu:16.04

RUN apt-get update && apt-get install -y chromium-browser curl gconf-service libgconf-2-4 libgtk2.0-0 && apt-get remove -y chromium-codecs-ffmpeg-extra && curl -L \
    https://launchpad.net/~canonical-chromium-builds/+archive/ubuntu/stage/+build/9852547/+files/chromium-browser_51.0.2704.79-0ubuntu0.16.04.1.1242_amd64.deb \
    > a.deb && curl -L \
    https://launchpad.net/~canonical-chromium-builds/+archive/ubuntu/stage/+build/9852547/+files/chromium-codecs-ffmpeg_51.0.2704.79-0ubuntu0.16.04.1.1242_amd64.deb \
    > b.deb && dpkg -i a.deb b.deb || true