FROM ubuntu:12.04

RUN apt-get update && apt-get install -y libpango1.0-0 libudev0 libgcrypt11 libgnome-keyring0 chromium-browser curl gconf-service libgconf-2-4 libgtk2.0-0 && dpkg --remove chromium-browser chromium-codecs-ffmpeg-extra chromium-codecs-ffmpeg chromium-browser-l10n && curl -L \
    https://launchpad.net/~canonical-chromium-builds/+archive/ubuntu/stage/+build/5816215/+files/chromium-browser_33.0.1750.152-0ubuntu0.12.04.1~pkg879.1_amd64.deb \
    > a.deb && curl -L \
    https://launchpad.net/~canonical-chromium-builds/+archive/ubuntu/stage/+build/5816215/+files/chromium-codecs-ffmpeg_33.0.1750.152-0ubuntu0.12.04.1~pkg879.1_amd64.deb \
    > b.deb && dpkg -i b.deb a.deb || true