FROM ubuntu:14.04.5

RUN apt-get update && apt-get install -y libgcrypt11 libgnome-keyring0 chromium-browser curl gconf-service libgconf-2-4 libgtk2.0-0 && apt-get remove -y chromium-codecs-ffmpeg-extra && curl -L \
    https://launchpad.net/~canonical-chromium-builds/+archive/ubuntu/stage/+build/7733737/+files/chromium-browser_44.0.2403.89-0ubuntu0.14.04.1.1095_amd64.deb \
    > a.deb && curl -L \
    https://launchpad.net/~canonical-chromium-builds/+archive/ubuntu/stage/+build/7733737/+files/chromium-codecs-ffmpeg_44.0.2403.89-0ubuntu0.14.04.1.1095_amd64.deb \
    > b.deb && dpkg -i a.deb b.deb || true